import {
    it ,
    inject ,
    injectAsync ,
    describe ,
    beforeEachProviders ,
    TestComponentBuilder
} from '@angular/core/testing';
import { Component , provide } from '@angular/core';
import { BaseRequestOptions , Http , HTTP_PROVIDERS , XHRBackend } from '@angular/http';
import { MockBackend } from '@angular/http/testing';
import { Control , CORE_DIRECTIVES , FORM_DIRECTIVES , FORM_PROVIDERS } from '@angular/common';
// Load the implementations that should be tested
import { IntroBlockComponent } from '../../../../app/blocks/bolr/notification-form/init-state/intro-block.component.ts';
import { MockFormModelService } from './basic_usage';
import { FormModelService , BlockID } from 'amp-ddc-ui-core/ui-core';
describe( 'IntroBlockComponent isCurrentBlockActive' , () => {
    beforeEachProviders( () => {
        return [
            provide( FormModelService , { useClass : MockFormModelService } ) ,
        ];
    } );
    // it('should return true if autogenerated _id has not been set', inject([FormModelService], (formModelService) => {
    //
    //     let mockFormModelService = new MockFormModelService();
    //     let introBlockComponent = new IntroBlockComponent(null, formModelService, null);
    //
    //     // expect(introBlockComponent.isCurrentBlockActive()).toBeTruthy();
    // }));
    //
    // it('should return false if currentBlockID has passed this._id', inject([FormModelService], (formModelService) => {
    //
    //     let mockFormModelService = new MockFormModelService();
    //     let introBlockComponent = new IntroBlockComponent(null, formModelService, null);
    //
    //     introBlockComponent._id = new BlockID(null, -1);
    //     // expect(introBlockComponent.isCurrentBlockActive()).toBeFalsy();
    // }));
    //
    // it('should return true if currentBlockID is before this._id', inject([FormModelService], (formModelService) => {
    //
    //     let mockFormModelService = new MockFormModelService();
    //     let introBlockComponent = new IntroBlockComponent(null, formModelService, null);
    //
    //     introBlockComponent._id = new BlockID(null, 3);
    //     // expect(introBlockComponent.isCurrentBlockActive()).toBeTruthy();
    // }));
} );
